### ISSUE TITLE
Homepage info in the Help menu is not correct

### ISSUE THREAD

**Issue by hwangcc23** [alexdantas/yetris#20]
The homepage info in the Help menu is "http://nsnake.alexdantas.net". (Should be "yetris.alexdantas.net".)
Need to correct it in src/Game/Display/WindowGameHelp.cpp.

![2014-12-31 9 27 47](https://cloud.githubusercontent.com/assets/1612266/5587886/faff9b32-9133-11e4-851a-6af89d0122eb.png)

**Comment by alexdantas** [comment]
You're right, I forgot about that.
There's so much code shared between `yetris` and `nsnake` you wouldn't believe all those tiny changes I have to make.
Thanks for spotting that and even more for specifying the exact file to change!
